name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate Javadoc
        run: mvn javadoc:javadoc --file pom.xml

      - name: Publish Javadoc to GitHub Pages
        if: success()
        run: |
          mkdir -p docs
          cp -R target/site/apidocs/* docs/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
